baseURL = "https://firetalk.rac.su"
languageCode = "en-us"
title = "Firebase workshop IWD18"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "GDG Zürich"
	description = "A demo hugo site for the firebase workshop"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/gdgzh/firebase-workshop-IWD18"

	version = "1.0.0"
	logo = "/img/wtm-logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "GDGZH"
	github  = "gdgzh"
	email   = ""


[[menu.main]]
	name   = "Workshop"
	url    = "/"
	weight = 0


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
